/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpo_mini_projet;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author saint
 */
public class InterfaceDemineurV2 extends javax.swing.JFrame {
private GrilleDeJeu grilleDeJeu;
    private  int nbLignes = 10;
    private  int nbColonnes = 10;
    private  int nbBombes = 10;
    /**
     * Creates new form InterfaceDemineurV2
     */
   public InterfaceDemineurV2() {
        initComponents();
        initialiserJeu(); // Initialise le jeu par défaut
    }
   
   

    // Méthode pour initialiser le jeu
    private void initialiserJeu() {
    grilleDeJeu = new GrilleDeJeu(nbLignes, nbColonnes, nbBombes);
    grilleDeJeu.calculerBombesAdjacentes();

    PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));

    for (int i = 0; i < nbLignes; i++) { 
        for (int j = 0; j < nbColonnes; j++) {
            final int i2 =i;
            final int j2 =j;
            // Récupérer la cellule correspondante dans la grille
            Cellule cellule = grilleDeJeu.getMatriceCellules()[i][j];

            // Créer un bouton CelluleGraphique en passant la cellule correspondante
            CelluleGraphique boutonCellule = new CelluleGraphique(i, j, cellule);

            // Ajouter un ActionListener pour gérer les clics
            boutonCellule.addActionListener(e -> {
                if (!cellule.getDevoilee()) {
                    // Révéler la cellule dans la grille
                    grilleDeJeu.revelerCellule(i2, j2);

                    // Mettre à jour l'affichage
                    mettreAJourAffichage();
                }
            });

            // Ajouter le bouton au panneau
            PanneauGrille.add(boutonCellule);
        }
    }

    PanneauGrille.revalidate(); // Re-valider et redessiner le panneau
    PanneauGrille.repaint();
}


    // Méthode pour mettre à jour l'affichage après un clic
    private void mettreAJourAffichage() {
        Cellule[][] cellules = grilleDeJeu.getMatriceCellules();
        
        // Parcourir chaque cellule de la grille et mettre à jour son affichage
        for (int i = 0; i < cellules.length; i++) {
            for (int j = 0; j < cellules[i].length; j++) {
                Cellule cellule = cellules[i][j];
                // Récupérer le bouton correspondant
                CelluleGraphique bouton = (CelluleGraphique) PanneauGrille.getComponent(i * nbColonnes + j);

                if (cellule.getDevoilee()) {
                    if (cellule.getPresenceBombe()) {
                        bouton.setText("B"); // Affiche une bombe
                    } else {
                        int nbBombesAdjacentes = cellule.getNbBombesAdjacentes();
                        bouton.setText(nbBombesAdjacentes > 0 ? String.valueOf(nbBombesAdjacentes) : "");
                    }
                    bouton.setEnabled(false);
                }
            }
        }
    }
// Méthode qui définit les paramètres de la grille en fonction de la difficulté
    public void ChoisirDifficulte(int difficulte) {
        switch (difficulte) {
            case 1: // Facile
                nbLignes = 8;
                nbColonnes = 8;
                nbBombes = 10;
                break;
            case 2: // Moyen
                nbLignes = 12;
                nbColonnes = 12;
                nbBombes = 20;
                break;
            case 3: // Difficile
                nbLignes = 16;
                nbColonnes = 16;
                nbBombes = 40;
                break;
            default:
                System.out.println("Difficulté non reconnue. Paramètres par défaut appliqués.");
                nbLignes = 10;
                nbColonnes = 10;
                nbBombes = 10;
                break;
        }
    }
    

            


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 204, 255));
        PanneauGrille.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PanneauGrille.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDemineurV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDemineurV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDemineurV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDemineurV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceDemineurV2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
