/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpo_mini_projet;

/**
 *
 * @author saint
 */
public class InterfaceDefaite extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceDefaite
     */
    public InterfaceDefaite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBM = new javax.swing.JButton();
        JBR = new javax.swing.JButton();
        JBD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("VOUS AVEZ PERDU!!!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 367, 164));

        JBM.setText("Menu");
        JBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMActionPerformed(evt);
            }
        });
        jPanel1.add(JBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 202, -1, -1));

        JBR.setText("Réssayer");
        JBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRActionPerformed(evt);
            }
        });
        jPanel1.add(JBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        JBD.setText("changer difficulté");
        JBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDActionPerformed(evt);
            }
        });
        jPanel1.add(JBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMActionPerformed
        // Aller à l'écran principal (menu principal ou nouvelle fenêtre)
    // Par exemple, tu pourrais créer une nouvelle instance de l'écran principal
    // Si tu veux revenir à un écran de menu principal, crée une nouvelle fenêtre ici
    // new MenuPrincipal().setVisible(true);
    this.dispose(); // Fermer la fenêtre actuelle
    }//GEN-LAST:event_JBMActionPerformed

    private void JBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRActionPerformed
        // Réinitialiser la grille de jeu et recommencer la partie
    // Par exemple, réinitialiser les variables, recréer la grille de jeu, etc.
    // new GrilleDeJeu(...).startGame();
    this.dispose(); // Fermer la fenêtre actuelle
    // Redémarrer le jeu
    // new Jeu().setVisible(true);  // Remplacer par ta logique pour relancer le jeu
    }//GEN-LAST:event_JBRActionPerformed

    private void JBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDActionPerformed
        // Ouvrir un écran pour changer la difficulté
    // new ChoisirDifficulte().setVisible(true);  // Par exemple, une nouvelle fenêtre pour choisir la difficulté
    this.dispose(); // Fermer la fenêtre actuelle
    }//GEN-LAST:event_JBDActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDefaite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBD;
    private javax.swing.JButton JBM;
    private javax.swing.JButton JBR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
